version: "2.4"

services:
  gitaly1repos:
    image: registry.gitlab.com/gitlab-org/gitlab-build-images:ruby-2.6-golang-1.12-git-2.22
    volumes:
      - gitalydata1:/repositories
      - ./gitaly1repos/setup.sh:/setup.sh
    restart: 'no'
    command: bash /setup.sh

  gitaly1:
    image: gitlab/gitaly:latest
    ports:
      - "9999:9999"
      - "9236:9236"
    environment:
      - TZ=UTC
    volumes:
      - ./gitaly1/config.toml:/app/config/config.toml
    volumes_from:
      - gitaly1repos
    cpus: 0.5
    mem_limit: 200m
    restart: unless-stopped

  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - 8080:8080
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    volumes:
      - promdata:/prometheus
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    links:
      - gitaly1
      - cadvisor
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    volumes:
      - grafdata:/var/lib/grafana
    ports:
      - 3000:3000
    links:
      - prometheus
    restart: unless-stopped

volumes:
  gitalydata1:
    driver: local
  grafdata:
    driver: local
  promdata:
    driver: local
