version: "3"
services:
  app1:
    image: gitlab/gitlab-ce:9.2.0-rc1.ce.0
    ports:
      - "8080:80"
      - "2222:22"
    links:
      - gitaly1
      - gitaly2
    volumes:
      - ./app1/etc-gitlab:/etc/gitlab
      - ./gitaly1/data:/mnt/data1
      - ./gitaly2/data:/mnt/data2
  gitaly1:
    image: gitlab/gitlab-ce:9.2.0-rc1.ce.0
    expose:
      - 6666
    volumes:
      - ./gitaly1/data:/var/opt/gitlab/git-data
      - ./gitaly1/etc-gitlab:/etc/gitlab
  gitaly2:
    image: gitlab/gitlab-ce:9.2.0-rc1.ce.0
    expose:
      - 6666
    volumes:
      - ./gitaly2/data:/var/opt/gitlab/git-data-2
      - ./gitaly2/etc-gitlab:/etc/gitlab
